import { bootstrapAdmin } from "../app.js";
import { confirmAction, createFormDialog } from "../components/dialogs.js";
import { showPageMessage } from "../components/admin-shell.js";
import { getCustomers } from "../services/customers.service.js";
import { getRefillingItems } from "../services/refilling-items.service.js";
import { createCertificate, deleteCertificate, getCertificate, getCertificatePdfUrl, getCertificates, updateCertificate } from "../services/certificates.service.js";
import { escapeHtml, normalizeSearch } from "../utils/formatters.js";

const root = await bootstrapAdmin("Certificates", "certificates", "Manage saved refilling certificates and next-refill dates");
const pageSize = 10; let certificates = []; let customers = []; let masters = []; let currentPage = 1; let itemKey = 0;
const formatDate = (value) => value ? new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${value}T00:00:00`)) : "—";
const statusLabel = (status) => ({ OVERDUE: "Overdue", DUE_TODAY: "Due Today", UPCOMING: "Upcoming" })[status] || "";
const statusBadge = (status) => status ? `<span class="badge text-bg-${status === "OVERDUE" ? "danger" : status === "DUE_TODAY" ? "warning" : "info"}">${statusLabel(status)}</span>` : "";

root.innerHTML = `<section class="admin-card" aria-labelledby="certificates-heading"><h2 id="certificates-heading" class="visually-hidden">Certificates</h2><div class="admin-toolbar"><input id="certificate-search" class="form-control admin-search" type="search" placeholder="Search certificate, customer or invoice" aria-label="Search certificates"><select id="certificate-status" class="form-select admin-filter" aria-label="Next-refill status"><option value="ALL">All</option><option value="UPCOMING">Upcoming</option><option value="DUE_TODAY">Due</option><option value="OVERDUE">Overdue</option></select></div><div id="certificate-table"></div></section>`;
document.querySelector("#admin-page-actions").innerHTML = `<button id="certificate-add" class="btn btn-danger"><i class="bi bi-plus-lg me-1"></i>Create Certificate</button>`; const table = root.querySelector("#certificate-table");

function filtered() { const term = normalizeSearch(root.querySelector("#certificate-search").value).replace(/\s+/g, " "); const status = root.querySelector("#certificate-status").value;
    return certificates.filter((item) => [item.certificateNumber, item.customerName, item.invoiceNumber].some((value) => normalizeSearch(value).replace(/\s+/g, " ").includes(term)))
        .filter((item) => status === "ALL" || item.items.some((entry) => entry.nextRefillStatus === status)).sort((a, b) => b.certificateDate.localeCompare(a.certificateDate)); }
function render() { const values = filtered(); const pages = Math.max(1, Math.ceil(values.length / pageSize)); currentPage = Math.min(currentPage, pages);
    const rows = values.slice((currentPage - 1) * pageSize, currentPage * pageSize).map((item) => `<tr><td>${escapeHtml(item.certificateNumber)}</td><td>${escapeHtml(item.customerName)}</td><td>${escapeHtml(item.invoiceNumber)}</td><td>${formatDate(item.certificateDate)}</td><td>${item.itemCount}</td><td>${formatDate(item.earliestNextRefillingDate)} ${statusBadge(item.nextRefillStatus)}</td><td class="admin-actions text-end"><button class="btn btn-sm btn-outline-secondary view" data-id="${escapeHtml(item.id)}" aria-label="View ${escapeHtml(item.certificateNumber)}"><i class="bi bi-eye"></i></button> <button class="btn btn-sm btn-outline-primary edit" data-id="${escapeHtml(item.id)}" aria-label="Edit ${escapeHtml(item.certificateNumber)}"><i class="bi bi-pencil"></i></button> <button class="btn btn-sm btn-outline-danger pdf" data-id="${escapeHtml(item.id)}" aria-label="Open PDF for ${escapeHtml(item.certificateNumber)}"><i class="bi bi-file-earmark-pdf"></i></button></td></tr>`).join("");
    table.innerHTML = `${rows ? `<div class="table-responsive"><table class="table admin-table align-middle"><thead><tr><th>Certificate No.</th><th>Customer</th><th>Invoice No.</th><th>Certificate Date</th><th>Items</th><th>Next Refill</th><th class="text-end">Actions</th></tr></thead><tbody>${rows}</tbody></table></div>` : `<div class="admin-empty"><i class="bi bi-file-earmark-check fs-2"></i><p class="mb-0">No Certificates found.</p></div>`}<nav class="admin-pagination" aria-label="Certificate pages"><button class="btn btn-outline-secondary previous" ${currentPage <= 1 ? "disabled" : ""}>Previous</button><span>Page ${currentPage} of ${pages}</span><button class="btn btn-outline-secondary next" ${currentPage >= pages ? "disabled" : ""}>Next</button></nav>`;
    table.querySelector(".previous").addEventListener("click", () => { currentPage--; render(); }); table.querySelector(".next").addEventListener("click", () => { currentPage++; render(); }); }
async function load() { table.innerHTML = `<div class="admin-loading"><span class="spinner-border text-danger"></span><span>Loading Certificates…</span></div>`; [customers, masters, certificates] = await Promise.all([getCustomers(), getRefillingItems(), getCertificates()]); render(); }

function options(records, currentId) { return records.filter((entry) => entry.isActive || entry.id === currentId).sort((a, b) => a.name.localeCompare(b.name)).map((entry) => `<option value="${escapeHtml(entry.id)}" ${entry.id === currentId ? "selected" : ""}>${escapeHtml(entry.name)}${entry.isActive ? "" : " (Inactive)"}</option>`).join(""); }
function itemBlock(item = null) { const key = ++itemKey; return `<fieldset class="certificate-item border rounded p-3" data-item-id="${escapeHtml(item?.id || "")}"><legend class="h6">Certificate Item</legend><div class="row g-3"><div class="col-md-6"><label class="form-label" for="ci-master-${key}">Refilling Item *</label><select class="form-select ci-master" id="ci-master-${key}" required><option value="">Select item</option>${options(masters, item?.refillingItemId)}</select></div><div class="col-md-3"><label class="form-label" for="ci-capacity-${key}">Capacity *</label><input class="form-control ci-capacity" id="ci-capacity-${key}" maxlength="120" value="${escapeHtml(item?.capacity || "")}" required></div><div class="col-md-3"><label class="form-label" for="ci-quantity-${key}">Quantity *</label><input class="form-control ci-quantity" id="ci-quantity-${key}" type="number" min="1" step="1" value="${item?.quantity || 1}" required></div><div class="col-md-6"><label class="form-label" for="ci-serials-${key}">Serial Numbers</label><textarea class="form-control ci-serials" id="ci-serials-${key}" rows="3">${escapeHtml((item?.serialNumbers || []).join("\n"))}</textarea><div class="form-text">One serial number per line.</div></div><div class="col-md-3"><label class="form-label" for="ci-refill-${key}">Refilling Date *</label><input class="form-control ci-refill" id="ci-refill-${key}" type="date" value="${escapeHtml(item?.refillingDate || "")}" required></div><div class="col-md-3"><label class="form-label" for="ci-next-${key}">Next Refilling Date *</label><input class="form-control ci-next" id="ci-next-${key}" type="date" value="${escapeHtml(item?.nextRefillingDate || "")}" required></div><div class="col-md-9"><label class="form-label" for="ci-remark-${key}">Remark</label><input class="form-control ci-remark" id="ci-remark-${key}" maxlength="1000" value="${escapeHtml(item?.remark || "")}"></div><div class="col-md-3 d-flex align-items-end"><button type="button" class="btn btn-outline-danger remove-item w-100">Remove</button></div></div></fieldset>`; }

function openEditor(certificate = null) { const customerOptions = options(customers, certificate?.customerId); const fields = `<div class="row g-3"><div class="col-md-6"><label class="form-label" for="cert-number">Certificate Number *</label><input class="form-control" id="cert-number" name="certificateNumber" maxlength="160" required></div><div class="col-md-6"><label class="form-label" for="cert-customer">Customer *</label><select class="form-select" id="cert-customer" name="customerId" required><option value="">Select customer</option>${customerOptions}</select></div><div class="col-md-6"><label class="form-label" for="cert-invoice">Invoice Number *</label><input class="form-control" id="cert-invoice" name="invoiceNumber" maxlength="160" required></div><div class="col-md-6"><label class="form-label" for="cert-date">Certificate Date *</label><input class="form-control" id="cert-date" name="certificateDate" type="date" required></div></div><div><div class="d-flex justify-content-between align-items-center mb-2"><h3 class="h6 mb-0">Refilling Items</h3><button type="button" class="btn btn-sm btn-outline-danger add-item"><i class="bi bi-plus-lg me-1"></i>Add Item</button></div><div class="certificate-items d-grid gap-3">${(certificate?.items || [null]).map(itemBlock).join("")}</div></div><div><label class="form-label" for="cert-remarks">Remarks</label><textarea class="form-control" id="cert-remarks" name="remarks" maxlength="2000" rows="3"></textarea></div>`;
    const dialog = createFormDialog(certificate ? "Edit Certificate" : "Create Certificate", fields); dialog.style.width = "min(96vw, 70rem)"; const form = dialog.querySelector("form"); form.querySelector(".submit-button").textContent = certificate ? "Save Changes" : "Save Certificate";
    if (certificate) { ["certificateNumber", "customerId", "invoiceNumber", "certificateDate", "remarks"].forEach((field) => { form.elements[field].value = certificate[field] || ""; }); }
    const container = dialog.querySelector(".certificate-items"); dialog.querySelector(".add-item").addEventListener("click", () => container.insertAdjacentHTML("beforeend", itemBlock()));
    container.addEventListener("click", (event) => { const button = event.target.closest(".remove-item"); if (button) button.closest(".certificate-item").remove(); });
    form.addEventListener("submit", async (event) => { event.preventDefault(); const blocks = [...container.querySelectorAll(".certificate-item")];
        if (!blocks.length) { dialog.querySelector(".dialog-message").innerHTML = '<div class="alert alert-danger">Add at least one Certificate Item.</div>'; return; }
        if (!form.checkValidity()) { form.classList.add("was-validated"); return; }
        const items = blocks.map((block) => ({ ...(block.dataset.itemId ? { id: block.dataset.itemId } : {}), refillingItemId: block.querySelector(".ci-master").value, capacity: block.querySelector(".ci-capacity").value.trim(), quantity: Number(block.querySelector(".ci-quantity").value), serialNumbers: block.querySelector(".ci-serials").value.split(/\r?\n/).map((value) => value.trim()).filter(Boolean), refillingDate: block.querySelector(".ci-refill").value, nextRefillingDate: block.querySelector(".ci-next").value, remark: block.querySelector(".ci-remark").value.trim() }));
        const data = { certificateNumber: form.elements.certificateNumber.value.trim(), customerId: form.elements.customerId.value, invoiceNumber: form.elements.invoiceNumber.value.trim(), certificateDate: form.elements.certificateDate.value, items, remarks: form.elements.remarks.value.trim() };
        const button = form.querySelector(".submit-button"); button.disabled = true; button.textContent = "Saving…";
        try { certificate ? await updateCertificate(certificate.id, data) : await createCertificate(data); dialog.close(); await load(); showPageMessage(`Certificate ${certificate ? "updated" : "created"}.`); }
        catch (error) { dialog.querySelector(".dialog-message").innerHTML = `<div class="alert alert-danger">${escapeHtml(error.message)}</div>`; button.disabled = false; button.textContent = certificate ? "Save Changes" : "Save Certificate"; }
    }); dialog.addEventListener("close", () => dialog.remove(), { once: true }); dialog.showModal(); }

async function openView(id) { try { const certificate = await getCertificate(id); const itemRows = certificate.items.map((item) => `<div class="border rounded p-3"><h3 class="h6">${escapeHtml(item.refillingItemName)} ${item.refillingItemActive ? "" : '<span class="badge text-bg-secondary">Inactive</span>'}</h3><dl class="row mb-0"><dt class="col-sm-4">Capacity</dt><dd class="col-sm-8">${escapeHtml(item.capacity)}</dd><dt class="col-sm-4">Quantity</dt><dd class="col-sm-8">${item.quantity}</dd><dt class="col-sm-4">Serial Numbers</dt><dd class="col-sm-8 text-break">${item.serialNumbers.length ? item.serialNumbers.map(escapeHtml).join("<br>") : "—"}</dd><dt class="col-sm-4">Refilling Date</dt><dd class="col-sm-8">${formatDate(item.refillingDate)}</dd><dt class="col-sm-4">Next Refilling Date</dt><dd class="col-sm-8">${formatDate(item.nextRefillingDate)} ${statusBadge(item.nextRefillStatus)}</dd><dt class="col-sm-4">Remark</dt><dd class="col-sm-8">${escapeHtml(item.remark || "—")}</dd></dl></div>`).join("");
        const body = `<dl class="row mb-0"><dt class="col-sm-4">Certificate Number</dt><dd class="col-sm-8">${escapeHtml(certificate.certificateNumber)}</dd><dt class="col-sm-4">Certificate Date</dt><dd class="col-sm-8">${formatDate(certificate.certificateDate)}</dd><dt class="col-sm-4">Customer</dt><dd class="col-sm-8">${escapeHtml(certificate.customerName)}</dd><dt class="col-sm-4">Customer Address</dt><dd class="col-sm-8 text-break">${escapeHtml(certificate.customerAddress || "—")}</dd><dt class="col-sm-4">Invoice Number</dt><dd class="col-sm-8">${escapeHtml(certificate.invoiceNumber)}</dd><dt class="col-sm-4">Remarks</dt><dd class="col-sm-8 text-break">${escapeHtml(certificate.remarks || "—")}</dd></dl><h3 class="h6 mt-3">Refilling Items</h3><div class="d-grid gap-2">${itemRows}</div><div class="d-flex flex-wrap gap-2 mt-3"><button type="button" id="certificate-pdf" class="btn btn-outline-danger"><i class="bi bi-file-earmark-pdf me-1"></i>Generate PDF</button><button type="button" id="delete-certificate" class="btn btn-outline-danger">Delete Certificate</button></div>`;
        const dialog = createFormDialog("View Certificate", body); dialog.style.width = "min(96vw, 70rem)"; const form = dialog.querySelector("form"); form.querySelector(".submit-button").textContent = "Edit Certificate"; form.addEventListener("submit", (event) => { event.preventDefault(); dialog.close(); openEditor(certificate); });
        dialog.querySelector("#certificate-pdf").addEventListener("click", () => window.open(getCertificatePdfUrl(certificate.id), "_blank", "noopener"));
        dialog.querySelector("#delete-certificate").addEventListener("click", async () => { dialog.close(); if (!await confirmAction("Delete this Certificate?", "This will permanently remove the Certificate and all of its saved item details. This action cannot be undone.", "Delete Certificate")) return; try { await deleteCertificate(certificate.id); await load(); showPageMessage("Certificate deleted."); } catch (error) { showPageMessage(error.message, "danger"); } });
        dialog.addEventListener("close", () => dialog.remove(), { once: true }); dialog.showModal(); } catch (error) { showPageMessage(error.message, "danger"); } }

root.querySelector("#certificate-search").addEventListener("input", () => { currentPage = 1; render(); }); root.querySelector("#certificate-status").addEventListener("change", () => { currentPage = 1; render(); });
document.querySelector("#certificate-add").addEventListener("click", () => openEditor()); table.addEventListener("click", (event) => { const button = event.target.closest("button[data-id]"); if (!button) return; const certificate = certificates.find((entry) => entry.id === button.dataset.id); if (!certificate) return; if (button.classList.contains("pdf")) window.open(getCertificatePdfUrl(certificate.id), "_blank", "noopener"); else if (button.classList.contains("view")) openView(certificate.id); else openEditor(certificate); });
try { await load(); } catch (error) { table.innerHTML = `<div class="alert alert-danger m-3">${escapeHtml(error.message)}</div>`; }
