import { bootstrapAdmin } from "../app.js";
import { changePassword } from "../services/auth.service.js";
import { getCsrfToken, redirectToLogin } from "../services/session.service.js";

const root=await bootstrapAdmin("Change Password","change-password","Update the password for the administrator account");
root.innerHTML=`<section class="admin-card admin-form-card"><p class="text-body-secondary">Use 12–128 characters with upper, lower, number, and symbol.</p><div id="form-message" role="status" aria-live="polite" hidden></div><form class="admin-form-fields" novalidate><div><label class="form-label" for="current-password">Current password</label><input class="form-control" id="current-password" type="password" autocomplete="current-password" required></div><div><label class="form-label" for="new-password">New password</label><input class="form-control" id="new-password" type="password" autocomplete="new-password" minlength="12" maxlength="128" required></div><div><label class="form-label" for="confirm-password">Confirm new password</label><input class="form-control" id="confirm-password" type="password" autocomplete="new-password" minlength="12" maxlength="128" required></div><div><button class="btn btn-danger" type="submit">Change password</button></div></form></section>`;
const form=root.querySelector("form"),current=root.querySelector("#current-password"),password=root.querySelector("#new-password"),confirmation=root.querySelector("#confirm-password"),button=form.querySelector("button"),message=root.querySelector("#form-message");
form.addEventListener("submit",async event=>{event.preventDefault();const strong=password.value.length>=12&&password.value.length<=128&&/[a-z]/.test(password.value)&&/[A-Z]/.test(password.value)&&/\d/.test(password.value)&&/[^a-zA-Z\d]/.test(password.value);if(!form.checkValidity()||!strong||password.value!==confirmation.value){show("Use 12–128 characters with upper, lower, number, and symbol; both passwords must match.","danger");return;}button.disabled=true;try{const result=await changePassword(current.value,password.value,confirmation.value,getCsrfToken());form.reset();show(result.message,"success");window.setTimeout(()=>redirectToLogin(),1200);}catch(error){form.reset();show(error.message||"Unable to change password.","danger");}finally{button.disabled=false;}});
function show(text,type){message.textContent=text;message.className=`alert alert-${type}`;message.hidden=false;}
