import { bootstrapAdmin } from "../app.js";
import { createRecord, deleteRecord, getCategories, getSubcategories, updateRecord } from "../services/catalog-admin.service.js";
import { createFormDialog, confirmAction } from "../components/dialogs.js";
import { showPageMessage } from "../components/admin-shell.js";
import { escapeHtml, normalizeSearch } from "../utils/formatters.js";

const root = await bootstrapAdmin("Subcategories", "subcategories", "Organize subcategories within catalogue categories"); let categories = [], records = [];
root.innerHTML = `<div class="admin-card"><div class="admin-toolbar"><input id="search" class="form-control admin-search" type="search" placeholder="Search subcategories" aria-label="Search subcategories"><select id="category-filter" class="form-select admin-filter" aria-label="Filter by category"><option value="">All categories</option></select></div><div id="table"></div></div>`;
document.querySelector("#admin-page-actions").innerHTML = `<button id="add" class="btn btn-danger"><i class="bi bi-plus-lg me-1"></i>Add subcategory</button>`;
const table = root.querySelector("#table"); const categoryName = (id) => categories.find((x) => x.id === id)?.name || "Unknown";
function render() { const term = normalizeSearch(root.querySelector("#search").value), category = root.querySelector("#category-filter").value; const rows = records.filter((x) => (!category || x.categoryId === category) && normalizeSearch(`${x.name} ${categoryName(x.categoryId)}`).includes(term)).sort((a,b)=>a.name.localeCompare(b.name)); table.innerHTML = rows.length ? `<div class="table-responsive"><table class="table admin-table align-middle"><thead><tr><th>Name</th><th>Category</th><th>ID</th><th class="text-end">Actions</th></tr></thead><tbody>${rows.map((x)=>`<tr><td>${escapeHtml(x.name)}</td><td>${escapeHtml(categoryName(x.categoryId))}</td><td>${x.id}</td><td class="admin-actions text-end"><button class="btn btn-sm btn-outline-primary edit" data-id="${x.id}" aria-label="Edit ${escapeHtml(x.name)}"><i class="bi bi-pencil"></i></button> <button class="btn btn-sm btn-outline-danger delete" data-id="${x.id}" aria-label="Delete ${escapeHtml(x.name)}"><i class="bi bi-trash"></i></button></td></tr>`).join("")}</tbody></table></div>` : `<div class="admin-empty">No subcategories found.</div>`; }
async function load() { table.innerHTML=`<div class="admin-loading"><span class="spinner-border text-danger"></span><span>Loading…</span></div>`; [categories,records]=await Promise.all([getCategories(),getSubcategories()]); root.querySelector("#category-filter").innerHTML=`<option value="">All categories</option>${categories.map(x=>`<option value="${x.id}">${escapeHtml(x.name)}</option>`).join("")}`; render(); }
function editor(record=null) { const options=categories.map(x=>`<option value="${x.id}">${escapeHtml(x.name)}</option>`).join(""); const dialog=createFormDialog(`${record?"Edit":"Add"} subcategory`,`<div class="mb-3"><label class="form-label" for="subcategory-category">Category</label><select id="subcategory-category" name="categoryId" class="form-select" required><option value="">Select category</option>${options}</select></div><div><label class="form-label" for="subcategory-name">Name</label><input id="subcategory-name" name="name" class="form-control" maxlength="160" required></div>`); if(record){dialog.querySelector("[name=categoryId]").value=record.categoryId;dialog.querySelector("[name=name]").value=record.name;} dialog.querySelector("form").addEventListener("submit",async(e)=>{e.preventDefault();if(!e.currentTarget.checkValidity()){e.currentTarget.classList.add("was-validated");return;}const button=e.currentTarget.querySelector(".submit-button");button.disabled=true;const data={categoryId:e.currentTarget.elements.categoryId.value,name:e.currentTarget.elements.name.value.trim()};try{record?await updateRecord("subcategories",{id:record.id,...data}):await createRecord("subcategories",data);dialog.close();await load();showPageMessage(`Subcategory ${record?"updated":"created"}.`);}catch(error){dialog.querySelector(".dialog-message").innerHTML=`<div class="alert alert-danger">${escapeHtml(error.message)}</div>`;button.disabled=false;}});dialog.addEventListener("close",()=>dialog.remove(),{once:true});dialog.showModal(); }
root.querySelector("#search").addEventListener("input",render); root.querySelector("#category-filter").addEventListener("change",render); document.querySelector("#add").addEventListener("click",()=>editor()); table.addEventListener("click",async(e)=>{const b=e.target.closest("button[data-id]");if(!b)return;const record=records.find(x=>x.id===b.dataset.id);if(b.classList.contains("edit"))return editor(record);if(await confirmAction("Delete subcategory?",`Delete “${record.name}”?`)){try{await deleteRecord("subcategories",record.id);await load();showPageMessage("Subcategory deleted.");}catch(error){showPageMessage(error.message,"danger");}}});
try{await load();}catch(error){table.innerHTML=`<div class="alert alert-danger">${escapeHtml(error.message)}</div>`;}
