<?php

declare(strict_types=1);
if (PHP_SAPI !== 'cli') exit(1);
$project=dirname(__DIR__);$root=sys_get_temp_dir().'/certificate-pdf-test-'.bin2hex(random_bytes(6));$private=$root.'/private';$cookies=$root.'/cookies';$server=null;$results=[];$password='Temporary-Test#2026';
function pdf_http(string $url,string $cookies,string $method='GET',?array $body=null):array{$out=tempnam(sys_get_temp_dir(),'pdf-body-');$headers=tempnam(sys_get_temp_dir(),'pdf-head-');$cmd=['curl','--silent','--show-error','--max-time','15','--dump-header',$headers,'--output',$out,'--write-out','%{http_code}','--cookie',$cookies,'--cookie-jar',$cookies,'--request',$method];if($body!==null)$cmd=[...$cmd,'--header','Content-Type: application/json','--data',json_encode($body,JSON_THROW_ON_ERROR)];$cmd[]=$url;$p=proc_open($cmd,[['pipe','r'],['pipe','w'],['pipe','w']],$pipes);if(!is_resource($p))throw new RuntimeException('Request failed.');fclose($pipes[0]);$status=stream_get_contents($pipes[1]);$error=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);if(proc_close($p)!==0)throw new RuntimeException((string)$error);$result=['status'=>(int)$status,'headers'=>(string)file_get_contents($headers),'body'=>(string)file_get_contents($out)];@unlink($headers);@unlink($out);return $result;}
function pdf_test(array &$results,string $label,callable $test):void{try{$results[$label]=$test()===true;}catch(Throwable){$results[$label]=false;}fwrite(STDOUT,($results[$label]?'PASS ':'FAIL ').$label.PHP_EOL);}
function pdf_remove(string $dir):void{if(!is_dir($dir))return;$items=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($items as $item)$item->isDir()&&!$item->isLink()?rmdir($item->getPathname()):unlink($item->getPathname());rmdir($dir);}
try{
 mkdir($private.'/business',0700,true);file_put_contents($private.'/admin.php',"<?php\nreturn ".var_export(['admin_email'=>'pdf@example.com','password_hash'=>password_hash($password,PASSWORD_DEFAULT),'credential_version'=>1],true).";\n");
 $customers=[['id'=>'CUS0001','name'=>'Test Industries Pvt Ltd & Engineering <Division>','address'=>'A long customer address, Industrial Estate, Solapur, Maharashtra - 413005','gstin'=>'','contactPerson'=>'','phone'=>'','email'=>'','isActive'=>false]];
 $masters=[['id'=>'RFI0001','name'=>'ABC Fire Extinguisher','isActive'=>false],['id'=>'RFI0002','name'=>'DCP Fire Extinguisher with Long Descriptive Type & Special <Text>','isActive'=>true]];
 $item=function(string $id,string $master,string $due,array $serials=[]):array{return ['id'=>$id,'refillingItemId'=>$master,'capacity'=>'9 KG','quantity'=>4,'serialNumbers'=>$serials,'refillingDate'=>'2026-08-25','nextRefillingDate'=>$due,'remark'=>'OK & serviced'];};
 $same=['id'=>'CERT0001','certificateNumber'=>'CERT/26-27/001','customerId'=>'CUS0001','invoiceNumber'=>'GST/26-27/0167','certificateDate'=>'2026-08-26','items'=>[$item('CIT0001','RFI0001','2027-08-24',['TQ/FE/ABC/08','TQ/FE/ABC/09']),$item('CIT0002','RFI0002','2027-08-24')],'remarks'=>'Certificate remarks with &, <, > and "quotes".'];
 $different=[...$same,'id'=>'CERT0002','certificateNumber'=>'CERT/26-27/002','items'=>[$item('CIT0001','RFI0001','2027-08-24'),$item('CIT0002','RFI0002','2027-09-15')]];
 $many=[];for($i=1;$i<=28;$i++)$many[]=$item('CIT'.str_pad((string)$i,4,'0',STR_PAD_LEFT),$i%2?'RFI0001':'RFI0002','2027-08-24',array_map(fn($n)=>'SERIAL/'.str_pad((string)$i,2,'0',STR_PAD_LEFT).'/'.$n,range(1,5)));
 $multi=[...$same,'id'=>'CERT0003','certificateNumber'=>'CERT/26-27/MULTI','items'=>$many,'remarks'=>'Final multi-page Certificate remarks.'];file_put_contents($private.'/business/customers.json',json_encode($customers,JSON_THROW_ON_ERROR));file_put_contents($private.'/business/refilling-items.json',json_encode($masters,JSON_THROW_ON_ERROR));file_put_contents($private.'/business/certificates.json',json_encode([$same,$different,$multi],JSON_THROW_ON_ERROR));
 $socket=stream_socket_server('tcp://127.0.0.1:0',$number,$message);if(!is_resource($socket))throw new RuntimeException($message,$number);$address=stream_socket_get_name($socket,false);fclose($socket);$port=(int)substr(strrchr((string)$address,':'),1);$server=proc_open([PHP_BINARY,'-S','127.0.0.1:'.$port,'-t',$project],[['pipe','r'],['file',$root.'/server.log','a'],['file',$root.'/server.log','a']],$pipes,$project,[...getenv(),'APP_PRIVATE_ROOT'=>$private]);if(!is_resource($server))throw new RuntimeException('Server failed.');fclose($pipes[0]);$base='http://127.0.0.1:'.$port;for($i=0;$i<30;$i++){usleep(100000);try{pdf_http($base.'/api/auth/session.php',$cookies);break;}catch(Throwable){}}
 $endpoint=$base.'/api/business/certificate-pdf.php';pdf_test($results,'unauthenticated request rejected',fn()=>pdf_http($endpoint.'?id=CERT0001',$cookies)['status']===401);$login=pdf_http($base.'/api/auth/login.php',$cookies,'POST',['password'=>$password]);
 foreach(['missing ID'=>$endpoint,'invalid ID'=>$endpoint.'?id=bad','unknown ID'=>$endpoint.'?id=CERT9999']as$label=>$url)pdf_test($results,$label.' controlled',fn()=>in_array(pdf_http($url,$cookies)['status'],[400,404],true));
 $samples=[];foreach(['single-page-certificate.pdf'=>'CERT0001','different-dates-certificate.pdf'=>'CERT0002','multi-page-certificate.pdf'=>'CERT0003']as$name=>$id){$response=pdf_http($endpoint.'?id='.$id,$cookies);$samples[$id]=$response;$output=$project.'/output/pdf';if(!is_dir($output))mkdir($output,0755,true);file_put_contents($output.'/'.$name,$response['body']);}
 $one=$samples['CERT0001'];pdf_test($results,'PDF headers, disposition and signature',fn()=>$one['status']===200&&stripos($one['headers'],'Content-Type: application/pdf')!==false&&stripos($one['headers'],'Content-Disposition: inline')!==false&&str_starts_with($one['body'],'%PDF-')&&strlen($one['body'])>5000);
 pdf_test($results,'exact title and formal sections present',fn()=>str_contains($one['body'],'C E R T I F I C A T E')&&str_contains($one['body'],'Type of Fire Extinguisher')&&str_contains($one['body'],'Authorised Signatory'));
 pdf_test($results,'same-date note and serial block present',fn()=>str_contains($one['body'],'NOTE: NEXT REFILLING DUE FOR ALL FIRE EXTINGUISHERS ON 24/08/2027.')&&str_contains($one['body'],'Serial Nos.: TQ/FE/ABC/08, TQ/FE/ABC/09'));
 pdf_test($results,'different-date note present',fn()=>str_contains($samples['CERT0002']['body'],'NOTE: NEXT REFILLING DATES ARE AS MENTIONED AGAINST EACH ITEM ABOVE.'));
 pdf_test($results,'saved-data-only request contract',fn()=>pdf_http($endpoint.'?id=CERT0001&certificateNumber=FORGED',$cookies)['status']===400&&pdf_http($endpoint.'?id=CERT0001',$cookies,'POST',['certificateNumber'=>'FORGED'])['status']===405);
 $multiBody=$samples['CERT0003']['body'];pdf_test($results,'multi-page PDF retains final content and one signature',fn()=>preg_match_all('/\/Type \/Page\b/',$multiBody)>1&&substr_count($multiBody,'Type of Fire Extinguisher')>1&&str_contains($multiBody,'Final multi-page Certificate remarks.')&&substr_count($multiBody,'Authorised Signatory')===1);
 pdf_test($results,'no payment or recreated invoice data',fn()=>!str_contains($one['body'],'Amount Received')&&!str_contains($one['body'],'Payment Status')&&!str_contains($one['body'],'CGST')&&!str_contains($one['body'],'HSN'));
 $broken=$same;$broken['customerId']='CUS9999';file_put_contents($private.'/business/certificates.json',json_encode([$broken],JSON_THROW_ON_ERROR));pdf_test($results,'missing Customer fails safely',fn()=>pdf_http($endpoint.'?id=CERT0001',$cookies)['status']===500);$broken=$same;$broken['items'][0]['refillingItemId']='RFI9999';file_put_contents($private.'/business/certificates.json',json_encode([$broken],JSON_THROW_ON_ERROR));pdf_test($results,'missing Refilling Item fails safely',fn()=>pdf_http($endpoint.'?id=CERT0001',$cookies)['status']===500);
 exit(in_array(false,$results,true)?1:0);
}finally{if(is_resource($server)){proc_terminate($server);proc_close($server);}pdf_remove($root);}
