<?php

declare(strict_types=1);
if (PHP_SAPI !== 'cli') exit(1);
$project = dirname(__DIR__); $root = sys_get_temp_dir() . '/certificate-api-test-' . bin2hex(random_bytes(6)); $private = $root . '/private'; $cookies = $root . '/cookies'; $server = null; $results = []; $password = 'Temporary-Test#2026';

function cert_http(string $url, string $cookies, string $method = 'GET', ?array $body = null, ?string $csrf = null): array {
    $output = tempnam(sys_get_temp_dir(), 'cert-response-'); $command = ['curl', '--silent', '--show-error', '--max-time', '10', '--output', $output, '--write-out', '%{http_code}', '--cookie', $cookies, '--cookie-jar', $cookies, '--request', $method];
    if ($body !== null) $command = [...$command, '--header', 'Content-Type: application/json', '--data', json_encode($body, JSON_THROW_ON_ERROR)]; if ($csrf !== null) $command = [...$command, '--header', 'X-CSRF-Token: ' . $csrf]; $command[] = $url;
    $process = proc_open($command, [['pipe', 'r'], ['pipe', 'w'], ['pipe', 'w']], $pipes); if (!is_resource($process)) throw new RuntimeException('Unable to request.'); fclose($pipes[0]); $status = stream_get_contents($pipes[1]); $error = stream_get_contents($pipes[2]); fclose($pipes[1]); fclose($pipes[2]); if (proc_close($process) !== 0) throw new RuntimeException((string) $error);
    $raw = (string) file_get_contents($output); @unlink($output); $json = json_decode($raw, true); return ['status' => (int) $status, 'json' => is_array($json) ? $json : [], 'raw' => $raw]; }
function cert_test(array &$results, string $label, callable $test): void { try { $results[$label] = $test() === true; } catch (Throwable) { $results[$label] = false; } fwrite(STDOUT, ($results[$label] ? 'PASS ' : 'FAIL ') . $label . PHP_EOL); }
function cert_remove(string $directory): void { if (!is_dir($directory)) return; $items = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($directory, FilesystemIterator::SKIP_DOTS), RecursiveIteratorIterator::CHILD_FIRST); foreach ($items as $item) $item->isDir() && !$item->isLink() ? rmdir($item->getPathname()) : unlink($item->getPathname()); rmdir($directory); }

try {
    mkdir($private . '/business', 0700, true); file_put_contents($private . '/admin.php', "<?php\nreturn " . var_export(['admin_email' => 'cert@example.com', 'password_hash' => password_hash($password, PASSWORD_DEFAULT), 'credential_version' => 1], true) . ";\n");
    $customers = [['id'=>'CUS0001','name'=>'Active Customer','address'=>'Pune','gstin'=>'','contactPerson'=>'','phone'=>'','email'=>'','isActive'=>true],['id'=>'CUS0002','name'=>'Inactive Customer','address'=>'Mumbai','gstin'=>'','contactPerson'=>'','phone'=>'','email'=>'','isActive'=>false]];
    $masters = [['id'=>'RFI0001','name'=>'ABC Fire Extinguisher','isActive'=>true],['id'=>'RFI0002','name'=>'CO2 Fire Extinguisher','isActive'=>true],['id'=>'RFI0003','name'=>'Inactive Item','isActive'=>false]];
    file_put_contents($private . '/business/customers.json', json_encode($customers, JSON_THROW_ON_ERROR)); file_put_contents($private . '/business/refilling-items.json', json_encode($masters, JSON_THROW_ON_ERROR));
    $socket = stream_socket_server('tcp://127.0.0.1:0', $number, $message); if (!is_resource($socket)) throw new RuntimeException($message, $number); $address = stream_socket_get_name($socket, false); fclose($socket); $port = (int) substr(strrchr((string) $address, ':'), 1);
    $server = proc_open([PHP_BINARY, '-S', '127.0.0.1:' . $port, '-t', $project], [['pipe','r'],['file',$root.'/server.log','a'],['file',$root.'/server.log','a']], $pipes, $project, [...getenv(), 'APP_PRIVATE_ROOT'=>$private]); if (!is_resource($server)) throw new RuntimeException('Server failed.'); fclose($pipes[0]); $base = 'http://127.0.0.1:' . $port; for ($i=0;$i<30;$i++){usleep(100000);try{cert_http($base.'/api/auth/session.php',$cookies);break;}catch(Throwable){}}
    $api = $base . '/api/admin/business/certificates.php'; cert_test($results, 'unauthenticated GET rejected', fn()=>cert_http($api,$cookies)['status']===401); cert_test($results, 'unauthenticated mutation rejected', fn()=>cert_http($api,$cookies,'POST',[])['status']===401);
    $login=cert_http($base.'/api/auth/login.php',$cookies,'POST',['password'=>$password]);$csrf=$login['json']['csrfToken']??'';if(!is_string($csrf)||$csrf==='')throw new RuntimeException('Login failed.'); cert_test($results,'missing CSRF rejected',fn()=>cert_http($api,$cookies,'POST',[])['status']===403); cert_test($results,'invalid CSRF rejected',fn()=>cert_http($api,$cookies,'POST',[],'bad')['status']===403);
    $tz=new DateTimeZone('Asia/Kolkata');$today=new DateTimeImmutable('today',$tz);$d=fn(int $days)=>$today->modify(($days<0?'':'+' ).$days.' days')->format('Y-m-d');
    $item=fn(string $master='RFI0001',int $quantity=4,string $next='')=>['refillingItemId'=>$master,'capacity'=>'9 KG','quantity'=>$quantity,'serialNumbers'=>[' ABC001 ','','ABC002','   '],'refillingDate'=>$d(-10),'nextRefillingDate'=>$next?:$d(10),'remark'=>' OK '];
    $valid=['certificateNumber'=>'CERT/26-27/001','customerId'=>'CUS0001','invoiceNumber'=>'EXTERNAL/001','certificateDate'=>$d(0),'items'=>[$item()],'remarks'=>' Note '];
    $created=cert_http($api,$cookies,'POST',$valid,$csrf);$id=$created['json']['data']['id']??'';$cit=$created['json']['data']['items'][0]['id']??'';
    cert_test($results,'valid create generates IDs and normalizes serials',fn()=>$created['status']===201&&$id==='CERT0001'&&$cit==='CIT0001'&&($created['json']['data']['items'][0]['serialNumbers']??[])===['ABC001','ABC002']);
    $stored=json_decode((string)file_get_contents($private.'/business/certificates.json'),true);cert_test($results,'stored schema excludes calculated fields',fn()=>array_keys($stored[0])===['id','certificateNumber','customerId','invoiceNumber','certificateDate','items','remarks']&&!isset($stored[0]['nextRefillStatus'])&&!isset($stored[0]['items'][0]['refillingItemName']));
    foreach (['missing number'=>array_diff_key($valid,['certificateNumber'=>1]),'blank number'=>[...$valid,'certificateNumber'=>' '],'unknown customer'=>[...$valid,'certificateNumber'=>'X1','customerId'=>'CUS9999'],'inactive customer'=>[...$valid,'certificateNumber'=>'X2','customerId'=>'CUS0002'],'blank invoice'=>[...$valid,'certificateNumber'=>'X3','invoiceNumber'=>' '],'bad date'=>[...$valid,'certificateNumber'=>'X4','certificateDate'=>'2026-02-30'],'missing items'=>array_diff_key($valid,['items'=>1]),'empty items'=>[...$valid,'items'=>[]],'client CERT ID'=>[...$valid,'id'=>'CERT9999']] as $label=>$body) cert_test($results,$label.' rejected',fn()=>cert_http($api,$cookies,'POST',$body,$csrf)['status']===400);
    foreach ([['unknown master',[...$item(),'refillingItemId'=>'RFI9999']],['inactive master',[...$item(),'refillingItemId'=>'RFI0003']],['blank capacity',[...$item(),'capacity'=>' ']],['zero quantity',[...$item(),'quantity'=>0]],['decimal quantity',[...$item(),'quantity'=>1.5]],['bad refill date',[...$item(),'refillingDate'=>'bad']],['next before refill',[...$item(),'nextRefillingDate'=>$d(-11)]],['non-string serial',[...$item(),'serialNumbers'=>[123]]]] as [$label,$bad]) cert_test($results,$label.' rejected',fn()=>cert_http($api,$cookies,'POST',[...$valid,'certificateNumber'=>'BAD-'.$label,'items'=>[$bad]],$csrf)['status']===400);
    cert_test($results,'normalized duplicate rejected',fn()=>cert_http($api,$cookies,'POST',[...$valid,'certificateNumber'=>' cert/26-27/001 '],$csrf)['status']===409);
    $multi=cert_http($api,$cookies,'POST',[...$valid,'certificateNumber'=>'CERT/002','items'=>[$item('RFI0001',10,$d(31)), $item('RFI0002',10,$d(-1))]],$csrf);$otherId=$multi['json']['data']['id']??'';$otherCit=$multi['json']['data']['items'][1]['id']??'';
    cert_test($results,'mixed status precedence and earliest date',fn()=>($multi['json']['data']['nextRefillStatus']??'')==='OVERDUE'&&($multi['json']['data']['earliestNextRefillingDate']??'')===$d(-1));
    foreach ([0=>'DUE_TODAY',1=>'UPCOMING',30=>'UPCOMING',31=>null] as $days=>$status){$response=cert_http($api,$cookies,'POST',[...$valid,'certificateNumber'=>'STATUS/'.$days,'items'=>[$item('RFI0001',1,$d($days))]],$csrf);cert_test($results,"status boundary $days days",fn()=>($response['json']['data']['nextRefillStatus']??null)===$status);}
    $updatedBody=[...$valid,'items'=>[['id'=>$cit,...$item('RFI0001',5,$d(20))],$item('RFI0002',2,$d(25))]];$updated=cert_http($api,$cookies,'PATCH',['id'=>$id,...$updatedBody],$csrf);
    cert_test($results,'edit preserves existing CIT and creates non-colliding new CIT',fn()=>$updated['status']===200&&($updated['json']['data']['items'][0]['id']??'')===$cit&&($updated['json']['data']['items'][1]['id']??'')==='CIT0002');
    cert_test($results,'remove item persists only retained item',function()use($api,$cookies,$csrf,$id,$valid,$cit,$item){$r=cert_http($api,$cookies,'PATCH',['id'=>$id,...$valid,'items'=>[['id'=>$cit,...$item()]],'remarks'=>'changed'],$csrf);return $r['status']===200&&count($r['json']['data']['items']??[])===1;});
    cert_test($results,'foreign CIT injection rejected',fn()=>cert_http($api,$cookies,'PATCH',['id'=>$id,...$valid,'items'=>[['id'=>$otherCit,...$item()]]],$csrf)['status']===400);
    cert_test($results,'same-number edit succeeds',fn()=>cert_http($api,$cookies,'PATCH',['id'=>$id,...$valid,'items'=>[['id'=>$cit,...$item()]]],$csrf)['status']===200); cert_test($results,'rename to duplicate rejected',fn()=>cert_http($api,$cookies,'PATCH',['id'=>$id,...$valid,'certificateNumber'=>' cert/002 '],$csrf)['status']===409);
    $customers[0]['isActive']=false;$masters[0]['isActive']=false;file_put_contents($private.'/business/customers.json',json_encode($customers,JSON_THROW_ON_ERROR));file_put_contents($private.'/business/refilling-items.json',json_encode($masters,JSON_THROW_ON_ERROR));
    cert_test($results,'historical inactive references remain readable/editable',function()use($api,$cookies,$csrf,$id,$valid,$cit,$item){$g=cert_http($api.'?id='.$id,$cookies);$u=cert_http($api,$cookies,'PATCH',['id'=>$id,...$valid,'items'=>[['id'=>$cit,...$item()]],'remarks'=>'history'],$csrf);return $g['status']===200&&$u['status']===200;});
    cert_test($results,'unrelated inactive customer rejected',fn()=>cert_http($api,$cookies,'PATCH',['id'=>$id,...$valid,'customerId'=>'CUS0002'], $csrf)['status']===400); cert_test($results,'new inactive master rejected on update',fn()=>cert_http($api,$cookies,'PATCH',['id'=>$id,...$valid,'items'=>[['id'=>$cit,...$item('RFI0003')]]],$csrf)['status']===400);
    cert_test($results,'DELETE requires CSRF',fn()=>cert_http($api,$cookies,'DELETE',['id'=>$id])['status']===403);$deleted=cert_http($api,$cookies,'DELETE',['id'=>$id],$csrf);cert_test($results,'delete removes only Certificate',fn()=>$deleted['status']===200&&cert_http($api.'?id='.$id,$cookies)['status']===404&&is_file($private.'/business/customers.json')&&is_file($private.'/business/refilling-items.json'));
    cert_test($results,'unknown delete rejected',fn()=>cert_http($api,$cookies,'DELETE',['id'=>'CERT9999'],$csrf)['status']===404);
    file_put_contents($private.'/business/certificates.json',json_encode([['id'=>'CERT0009']],JSON_THROW_ON_ERROR));cert_test($results,'invalid stored schema controlled without reset/path leak',function()use($api,$cookies,$private){$before=file_get_contents($private.'/business/certificates.json');$r=cert_http($api,$cookies);return $r['status']===500&&file_get_contents($private.'/business/certificates.json')===$before&&!str_contains($r['raw'],$private);});
    exit(in_array(false,$results,true)?1:0);
} finally { if(is_resource($server)){proc_terminate($server);proc_close($server);} cert_remove($root); }
